Mgt_Project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("", include("mgt_app.urls")),
    path("admin/", admin.site.urls),
]

mgt_app/urls.py
from django.urls import path
from . import views

app_name = "mgt_app"
urlpatterns = [

    path("", views.index, name="index"),
    path("products/", views.products, name="products"),
    path("customers/<str:pk>/", views.customers, name="customers"),
    path("createorder/<str:pk>/", views.createOrder, name="createorder"),
    path("update_order/<str:pk>/", views.updateOrder, name="update_order"),
    path("delete_order/<str:pk>/", views.deleteOrder, name="delete_order"),
    
]

mgt_app/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=200, null=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    CATEGORY = (
        ("indoor", "indoor"),
        ("outdoor", "outdoor"),
    )

    name = models.CharField(max_length=200, null=True)
    price = models.FloatField(null=True)
    category = models.CharField(max_length=200, null=True, choices=CATEGORY)
    description = models.CharField(max_length=200, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    tag = models.ManyToManyField(Tag)

    def __str__(self):
        return self.name


class Order(models.Model):
    STATUS = (
        ("Pending", "Pending"),
        ("Out of order", "Out of order"),
        ("Delivered", "Delivered"),
    )
    customer = models.ForeignKey(Customer, null=True, on_delete=models.SET_NULL)
    product = models.ForeignKey(Product, null=True, on_delete=models.SET_NULL)

    date_added = models.DateTimeField(auto_now_add=True, null=True)
    status = models.CharField(max_length=200, null=True, choices=STATUS)

    def __str__(self):
        return self.product.name
 

mgt_app/forms.py
from django.forms import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        fields = "__all__"

mgt_app/views.py
from django.shortcuts import render, redirect
from django.forms import inlineformset_factory
from .models import *
from .forms import OrderForm


def index(request):
    orders = Order.objects.all()
    customers = Customer.objects.all()

    total_orders = orders.count()
    total_customers = customers.count()
    delivered = orders.filter(status="Delivered").count()
    pending = orders.filter(status="pending").count()

    context = {
        "orders": orders,
        "customers": customers,
        "total_orders": total_orders,
        "total_customers": total_customers,
        "delivered": delivered,
        "pending": pending,
    }

    return render(request, "mgt_app/index.html", context)


def products(request):
    products = Product.objects.all()
    context = {"products": products}
    return render(request, "mgt_app/products.html", context)


def customers(request, pk):
    customer = Customer.objects.get(id=pk)
    orders = customer.order_set.all()
    total_orders = orders.count()

    context = {"orders": orders, "customer": customer, "total_orders": total_orders}
    return render(request, "mgt_app/customers.html", context)


def createOrder(request, pk):
    OrderFormSet = inlineformset_factory(Customer, Order, fields=('product', 'status'))
    customer = Customer.objects.get(id=pk)
    #form = OrderForm(initial={'customer':customer})
    formset = OrderFormSet(queryset=Order.objects.none(), instance=customer)
    if request.method == "POST":
       # form = OrderForm(data=request.POST)
        formset = OrderFormSet(request.POST, instance=customer)
        if formset.is_valid:
            formset.save()
            return redirect("/")

    context = {"formset": formset}
    return render(request, "mgt_app/order_form.html", context)


def updateOrder(request, pk):
    order = Order.objects.get(id=pk)
    form = OrderForm(instance=order)
    if request.method == "POST":
        form = OrderForm(data=request.POST, instance=order)
        if form.is_valid:
            form.save()
            return redirect("/")

    context = {"form": form}
    return render(request, "mgt_app/order_form.html", context)


def deleteOrder(request, pk):
    order = Order.objects.get(id=pk)
    if request.method == 'POST':
        order.delete()
        return redirect('/')

    context = {'item': order}
    return render(request, "mgt_app/delete.html", context)

mgt_app/templates/mgt_app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">

    <title> Customer Management App</title>

</head>

<body>
    {% include 'mgt_app/navbar.html' %}

    {% block content %}
    {% endblock content %}


</body>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>

</html>

mgt_app/templates/mgt_app/customers.html
{% extends "mgt_app/base.html" %}

{% block content %}

<br>
<div class="row">
    <div class="col -md">
        <div class="card card-body">
            <h5>Customer</h5>
            <hr>
            <a class="btn btn-outline-info btn-sm btn-block" href="">Update Customer</a>
            <a class="btn btn-outline-info btn-sm btn-block" href="{% url 'mgt_app:createorder' customer.id %}">Place Order</a>
            <a href=""></a>
        </div>
    </div>
    <div class="col-md">
        <div class="card card-body">
            <h5>Contact Information</h5>
            <hr>
            <p>Email: {{customer.email}}</p>
            <p>Phone: {{customer.phone}}</p>
        </div>
    </div>

    <div class="col-md">
        <div class="card card-body">
            <h5>Total Orders</h5>
            <hr>
            <h1 style="text-align: center; padding: 10px">{{total_orders}}</h1>
        </div>
    </div>
</div>

<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove</th>
                </tr>

                {% for order in orders %}
                    <tr>
                        <td> {{order.product}} </td>
                        <td> {{order.product.category}} </td>
                        <td> {{order.date_added}} </td>
                        <td> {{order.status}} </td>
                        <td> <a class="btn btn-sm btn-info" href="{% url 'mgt_app:update_order' order.id  %}">Update</a>
                        </td>
                        <td> <a class="btn btn-sm btn-danger" href="{% url 'mgt_app:delete_order' order.id %}">Delete</a>
                        </td> 
                    </tr>
                {% endfor %}

            </table>
        </div>
    </div>
</div>

{% endblock content %}

mgt_app/templates/mgt_app/delete.html
{% extends "mgt_app/base.html" %}
{% load static %}
{% block content %}
 
<br>
<div class="row">
    <div class="col-md-6">
        <div class="card card-body">

            <p>Are you sure you want to delete {{item}}</p>

            <form action="{% url 'mgt_app:delete_order' item.id %}" method="POST">

                {% csrf_token %}
                <a href="{% url 'mgt_app:index' %}">Cancel</a>
                <input class="btn btn-warning" type="submit" value="confirm">
            </form> 
        </div>
    </div>
</div>


{% endblock %}

mgt_app/templates/mgt_app/index.html
{% extends 'mgt_app/base.html' %}

{% block content %}

{% include 'mgt_app/status.html' %}
<br>

<div class="row">
    <div class="col-md-5">
        <h5>CUSTOMERS:</h5>
        <hr>
        <div class="card card-body">

            <a class="btn btn-primary btn-sm btn-block" href="">Create Customer</a>
            <table class="table table-sm">
                <tr>
                    <th>Customer</th>
                    <th>Phone</th>
                </tr>
                {% for customer in customers %}
                <tr>
                    <td><a class="btn btn-sm btn-info" href="{% url 'mgt_app:customers' customer.id%}">View</a></td>
                    <td> {{customer.name}} </td>
                    <td> {{customer.phone}} </td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>

    <div class="col-md-7">
        <h5>LAST 5 ORDERS</h5>
        <hr>
        <div class="card card-body">
            <table class="table table-sm">
                <tr>
                    <th>Product</th>
                    <th>Date Ordered</th>
                    <th>Status</th>
                    <th>Update</th>
                    <th>Remove </th>
                </tr>

                {% for order in orders %}
                <tr>
                    <td> {{order.product}} </td>
                    <td> {{order.date_added|date:"F j, Y"}} </td>
                    <td> {{order.status}} </td>
                    <td> <a class="btn btn-sm btn-info" href="{% url 'mgt_app:update_order' order.id  %}">Update</a>
                    </td>
                    <td> <a class="btn btn-sm btn-danger" href="{% url 'mgt_app:delete_order' order.id %}">Delete</a>
                    </td>
                </tr>
                {% endfor %}


            </table>
        </div>
    </div>
</div>


{% endblock content %}

mgt_app/templates/mgt_app/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'mgt_app:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'mgt_app:products' %}">Products</a>
        </li>
      </ul>
    </div>
  </nav>

mgt_app/templates/mgt_app/order_form.html
 {% extends "mgt_app/base.html" %}
 {% load static %}
 {% block content %}

 <div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{formset.management_form}}
                {% for form in formset %}
              
                    {{form}}
                    <br>
                {% endfor %}
                <input type='submit' name='submit' value="submit">
            </form>
        </div>
    </div>
 </div>

 {% endblock content %}
 

mgt_app/templates/mgt_app/products.html
{% extends 'mgt_app/base.html' %}

{% block content %}

<br>
<div class="row">
    <div class="col-md">
        <div class="card card-body">
            <h5>Products</h5>
        </div>
        <div class="card card-body">
            <table class="table">
                <tr>
                    <th>Product</th>
                    <th>Category</th>
                    <th>Price</th>
                </tr>

                {% for product in products %}
                    <tr>
                        <td> {{product.name}}</td>
                        <td> {{product.category}}</td>
                        <td> {{product.price}}</td>
                    </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>

{% endblock content %}

mgt_app/templates/mgt_app/status.html
<br>
<div class="row">
    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="total-orders">
                <div class="card-header">
                    <h5 class="card-title">Total Orders</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{total_orders}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="cols">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-delivered">
                <div class="card-header">
                    <h5 class="card-title">Orders Delivered</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title">{{delivered}}</h3>
                </div>
            </div>
        </div>
    </div>

    <div class="col">
        <div class="col-md">
            <div class="card text-center text-white mb-3" id="orders-pending">
                <div class="card-header">
                    <h5 class="card-title">Orders Pending</h5>
                </div>
                <div class="card-body">
                    <h3 class="card-title"> {{pending}} </h3>
                </div>
            </div>
        </div>
    </div>
</div>